name: Polaris Scan on helm Manifests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'hipster/helm-chart/**'
  pull_request:
    branches:
      - main
    paths:
      - 'hipster/helm-chart/**'

jobs:
  polaris-scan:
    runs-on: ubuntu-latest
    name: "Run Polaris Scan"
    steps:
      - name: Checkout using Personal Access Token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Debug Chart Path
        run: ls -R ./hipster/helm-chart

      - name: Render Helm chart
        run: |
          mkdir -p rendered
          helm template hipster-shop ./hipster/helm-chart --namespace hipster > rendered/all.yaml
    
      - name: Run Polaris scan on rendered output
        run: |
          echo "ğŸ” Running Polaris scan on rendered YAMLs..."
          docker run --rm \
            -v "${{ github.workspace }}/rendered:/manifests" \
            quay.io/fairwinds/polaris:latest \
            polaris audit --audit-path /manifests \
            --format pretty \
            --set-exit-code-on-danger

      - name: Upload Polaris Report
        uses: actions/upload-artifact@v4
        with:
          name: polaris-scan-results
          path: rendered/all.yaml


