name: Update run config
env:
  GH_PAT: ${{ secrets.GH_PAT }}
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service Name (e.g. adservice)'
        required: true
      image_tag:
        description: 'New Image Tag (e.g. v0.3.0)'
        required: true

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Update Image Tag
      run: |
        file="hipster/kubernetes-manifests/${{ github.event.inputs.service }}.yaml"
        if [ ! -f "$file" ]; then
          echo "âŒ File not found: $file"
          exit 1
        fi

        echo "ğŸ”„ Updating $file..."
        sed -i "s|\(image: .*${{ github.event.inputs.service }}:\).*|\1${{ github.event.inputs.image_tag }}|" "$file"
        echo "âœ… Updated image tag in $file"

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
        git commit -am "ğŸ”„ Update adservice to ${{ github.event.inputs.image_tag }}"
        git push origin HEAD:${{ github.ref_name }}
